{
  "hash": "89e78b9a4eafabb3117951980f00112e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 2\"\nsubtitle: \"Beyond ggplot2 Fundamentals\"\nauthor: \"Thi Thanh Van Tran\"\ndate: \"April 22, 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    number-depth: 3\n    code-fold: false\n    code-tools: true\n    code-copy: true\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# Overview\n\nIn this hands-on exercise, I will explore several **ggplot2 extensions** for creating more elegant and effective statistical graphics. By the end of this exercise, I will be able to:\n\n-   Control the placement of annotation on a graph by using functions provided in **ggrepel** package\n-   Create professional publication quality figures by using functions provided in **ggthemes** and **hrbrthemes** packages\n-   Plot composite figures by combining ggplot2 graphs using **patchwork** package\n\nAdditionally, I will conduct **comprehensive data-driven analysis** with dynamic insights extracted directly from the examination results.\n\n# Getting Started\n\n## Installing and Loading Required Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(ggrepel, patchwork, \n               ggthemes, hrbrthemes,\n               tidyverse, \n               GGally, viridis, ggridges, scales, gridExtra)\n```\n:::\n\n\n## Importing Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexam_data <- read_csv(\"data/Exam_data.csv\")\n```\n:::\n\n\n## Initial Data Exploration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(exam_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 322\nColumns: 7\n$ ID      <chr> \"Student321\", \"Student305\", \"Student289\", \"Student227\", \"Stude…\n$ CLASS   <chr> \"3I\", \"3I\", \"3H\", \"3F\", \"3I\", \"3I\", \"3I\", \"3I\", \"3I\", \"3H\", \"3…\n$ GENDER  <chr> \"Male\", \"Female\", \"Male\", \"Male\", \"Male\", \"Female\", \"Male\", \"M…\n$ RACE    <chr> \"Malay\", \"Malay\", \"Chinese\", \"Chinese\", \"Malay\", \"Malay\", \"Chi…\n$ ENGLISH <dbl> 21, 24, 26, 27, 27, 31, 31, 31, 33, 34, 34, 36, 36, 36, 37, 38…\n$ MATHS   <dbl> 9, 22, 16, 77, 11, 16, 21, 18, 19, 49, 39, 35, 23, 36, 49, 30,…\n$ SCIENCE <dbl> 15, 16, 16, 31, 25, 16, 25, 27, 15, 37, 42, 22, 32, 36, 35, 45…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(exam_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ID               CLASS              GENDER              RACE          \n Length:322         Length:322         Length:322         Length:322        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n    ENGLISH          MATHS          SCIENCE     \n Min.   :21.00   Min.   : 9.00   Min.   :15.00  \n 1st Qu.:59.00   1st Qu.:58.00   1st Qu.:49.25  \n Median :70.00   Median :74.00   Median :65.00  \n Mean   :67.18   Mean   :69.33   Mean   :61.16  \n 3rd Qu.:78.00   3rd Qu.:85.00   3rd Qu.:74.75  \n Max.   :96.00   Max.   :99.00   Max.   :96.00  \n```\n\n\n:::\n:::\n\n\n### Data Quality Assessment\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate data quality metrics\nn_students <- nrow(exam_data)\nn_complete_cases <- sum(complete.cases(exam_data))\nmissing_counts <- colSums(is.na(exam_data))\ncompleteness_rate <- (n_complete_cases / n_students) * 100\n```\n:::\n\n\n::: callout-note\n## Data Quality Summary\n\nThe dataset contains **322 students** with **7 variables**.\n\nData completeness: **100%** of cases have no missing values.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nNo missing values detected - dataset is complete and ready for analysis.\n```\n\n\n:::\n:::\n\n:::\n\n### Categorical Variable Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze categorical distributions\ngender_dist <- table(exam_data$GENDER)\nrace_dist <- table(exam_data$RACE)\nclass_dist <- table(exam_data$CLASS)\n\n# Calculate proportions\ngender_prop <- prop.table(gender_dist) * 100\nrace_prop <- prop.table(race_dist) * 100\nclass_prop <- prop.table(class_dist) * 100\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Gender Distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGender Distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(gender_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFemale   Male \n   170    152 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nRace Distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRace Distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(race_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nChinese  Indian   Malay  Others \n    193      12     108       9 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nClass Distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nClass Distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(class_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n3A 3B 3C 3D 3E 3F 3G 3H 3I \n40 38 39 38 38 39 34 33 23 \n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Sample Composition Analysis\n\n**Gender Balance:** The dataset contains 170 (52.8%) Female students and 152 (47.2%) Male students. The gender distribution is relatively balanced.\n\n**Diversity:** The sample includes 4 different racial groups, with Chinese being the largest group at 59.9%.\n\n**Class Distribution:** Students are distributed across 9 classes, with class sizes ranging from 23 to 40 students.\n:::\n\n# Beyond ggplot2 Annotation: ggrepel\n\n## The Problem: Overlapping Labels\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=exam_data, \n       aes(x= MATHS, \n           y=ENGLISH)) +\n  geom_point() +\n  geom_smooth(method=lm, size=0.5) +  \n  geom_label(aes(label = ID), hjust = .5, vjust = -.5) +\n  coord_cartesian(xlim=c(0,100), ylim=c(0,100)) +\n  ggtitle(\"English scores versus Maths scores for Primary 3\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate correlation for interpretation\ncor_maths_english <- cor(exam_data$MATHS, exam_data$ENGLISH)\n```\n:::\n\n\n::: callout-warning\n## Visualization Issue Identified\n\nThe scatter plot above demonstrates a **critical labeling problem**: with 322 data points, the labels overlap significantly, making individual student IDs **impossible to read**.\n\nThe plot does show a positive correlation (r = 0.831) between Mathematics and English scores, but the overlapping labels obscure this insight and make the visualization **ineffective for identifying individual students**.\n:::\n\n## The Solution: Using ggrepel\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=exam_data, \n       aes(x= MATHS, \n           y=ENGLISH)) +\n  geom_point() +\n  geom_smooth(method=lm, size=0.5) +  \n  geom_label_repel(aes(label = ID), fontface = \"bold\") +\n  coord_cartesian(xlim=c(0,100), ylim=c(0,100)) +\n  ggtitle(\"English scores versus Maths scores for Primary 3\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-11-1.png){width=768}\n:::\n:::\n\n\n::: callout-tip\n## Improvement Achieved\n\nUsing `geom_label_repel()` instead of `geom_label()` successfully **eliminates label overlap** through intelligent automatic positioning. Each of the 322 student IDs is now **readable and traceable** to its corresponding data point, while maintaining the visualization of the strong positive correlation (r = 0.831) between subjects.\n:::\n\n## Extended Analysis: Selective Labeling Strategy\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate performance metrics\nexam_data_labeled <- exam_data %>%\n  mutate(\n    total_score = MATHS + ENGLISH + SCIENCE,\n    performance_label = case_when(\n      total_score >= quantile(total_score, 0.9) ~ ID,\n      total_score <= quantile(total_score, 0.1) ~ ID,\n      TRUE ~ \"\"\n    )\n  )\n\n# Identify thresholds\ntop_10_threshold <- quantile(exam_data_labeled$total_score, 0.9)\nbottom_10_threshold <- quantile(exam_data_labeled$total_score, 0.1)\nn_labeled <- sum(exam_data_labeled$performance_label != \"\")\n\nggplot(data=exam_data_labeled, \n       aes(x= MATHS, y=ENGLISH)) +\n  geom_point(aes(color = total_score), size = 3, alpha = 0.6) +\n  geom_smooth(method=lm, size=0.5, color = \"darkblue\") +  \n  geom_label_repel(\n    aes(label = performance_label), \n    fontface = \"bold\",\n    box.padding = 0.5,\n    point.padding = 0.3,\n    segment.color = 'grey50',\n    max.overlaps = 20\n  ) +\n  scale_color_viridis_c(option = \"plasma\") +\n  coord_cartesian(xlim=c(0,100), ylim=c(0,100)) +\n  labs(\n    title = \"English vs Maths: Top/Bottom 10% Performers Labeled\",\n    subtitle = \"Color gradient shows total score across all subjects\",\n    x = \"Mathematics Score\",\n    y = \"English Score\",\n    color = \"Total Score\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n::: callout-note\n## Strategic Labeling Analysis\n\n**Selective Approach:** Instead of labeling all 322 students, this visualization strategically labels only **68 students** (21.1% of the sample) - specifically the top and bottom 10% performers.\n\n**Performance Thresholds:** - **Top 10%:** Total score ≥ 254 points - **Bottom 10%:** Total score ≤ 118.2 points\n\n**Key Insight:** The color gradient reveals that high performers in Mathematics tend to also score high in English (note the concentration of yellow/bright points in the upper-right quadrant), confirming the strong correlation (r = 0.831) and suggesting that academic ability is **relatively consistent across subjects** for exceptional students.\n:::\n\n## Gender-Based Performance Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate gender-specific correlations and statistics\ngender_stats <- exam_data %>%\n  group_by(GENDER) %>%\n  summarise(\n    n = n(),\n    cor_me = cor(MATHS, ENGLISH),\n    mean_maths = mean(MATHS),\n    mean_english = mean(ENGLISH)\n  )\n\nggplot(data=exam_data, \n       aes(x= MATHS, y=ENGLISH, color = GENDER)) +\n  geom_point(size = 3, alpha = 0.6) +\n  geom_smooth(method=lm, se = TRUE, alpha = 0.2) +  \n  scale_color_manual(values = c(\"#E69F00\", \"#56B4E9\")) +\n  coord_cartesian(xlim=c(0,100), ylim=c(0,100)) +\n  labs(\n    title = \"English vs Maths Performance by Gender\",\n    subtitle = \"Separate regression lines for each gender group\",\n    x = \"Mathematics Score\",\n    y = \"English Score\",\n    color = \"Gender\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate slope differences\nlm_male <- lm(ENGLISH ~ MATHS, data = filter(exam_data, GENDER == \"Male\"))\nlm_female <- lm(ENGLISH ~ MATHS, data = filter(exam_data, GENDER == \"Female\"))\nslope_male <- coef(lm_male)[2]\nslope_female <- coef(lm_female)[2]\n```\n:::\n\n\n::: callout-important\n## Gender Comparison Insights\n\n**Sample Sizes:** 152 Male students vs 170 Female students.\n\n**Correlation Strength:** - Male students: r = 0.828 - Female students: r = 0.853\n\n**Performance Patterns:** - **Mathematics:** Males averaged 68.6 vs Females 70 (difference: 1.4 points) - **English:** Males averaged 64.3 vs Females 69.8 (difference: 5.5 points)\n\n**Regression Analysis:** The slope of the relationship differs slightly (0.595 for males vs 0.621 for females), suggesting similar performance patterns.\n:::\n\n# Beyond ggplot2 Themes\n\n## Built-in Theme Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate distribution statistics for interpretation\nmaths_mean <- mean(exam_data$MATHS)\nmaths_median <- median(exam_data$MATHS)\nmaths_sd <- sd(exam_data$MATHS)\nskewness <- (maths_mean - maths_median) / maths_sd\n\nggplot(data=exam_data, aes(x = MATHS)) +\n  geom_histogram(bins=20, boundary = 100,\n                 color=\"grey25\", fill=\"grey90\") +\n  theme_gray() +\n  ggtitle(\"Distribution of Maths scores\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-15-1.png){width=768}\n:::\n:::\n\n\n::: callout-note\n## Distribution Characteristics\n\n**Central Tendency:** Mean = 69.3, Median = 74\n\n**Spread:** Standard deviation = 20 points\n\n**Shape:** The distribution shows slight negative skewness (left tail) with skewness coefficient of -0.234.\n:::\n\n## Professional Themes: ggthemes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=exam_data, aes(x = MATHS)) +\n  geom_histogram(bins=20, boundary = 100,\n                 color=\"grey25\", fill=\"grey90\") +\n  ggtitle(\"Distribution of Maths scores\") +\n  theme_economist()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-16-1.png){width=768}\n:::\n:::\n\n\n::: callout-tip\n## Theme Selection Rationale\n\nThe **Economist theme** provides a professional, publication-ready aesthetic suitable for business and academic contexts. This theme emphasizes clarity and readability, making it ideal for presenting the Mathematics score distribution (μ = 69.3, σ = 20) to stakeholders.\n:::\n\n## Typography-Focused: hrbrthemes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=exam_data, aes(x = MATHS)) +\n  geom_histogram(bins=20, boundary = 100,\n                 color=\"grey25\", fill=\"grey90\") +\n  ggtitle(\"Distribution of Maths scores\") +\n  theme_ipsum()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-17-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=exam_data, aes(x = MATHS)) +\n  geom_histogram(bins=20, boundary = 100,\n                 color=\"grey25\", fill=\"grey90\") +\n  ggtitle(\"Distribution of Maths scores\") +\n  theme_ipsum(axis_title_size = 18, base_size = 15, grid = \"Y\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-18-1.png){width=768}\n:::\n:::\n\n\n::: callout-tip\n## Customization Impact\n\nThe customized `theme_ipsum()` with larger fonts (axis titles: 18pt, base: 15pt) and Y-only gridlines improves **readability** while reducing visual clutter. This is particularly effective for presentations where the audience needs to quickly grasp the distribution pattern showing most students cluster around the mean of 69.3 points.\n:::\n\n## Theme Effectiveness Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreate_themed_plot <- function(theme_name, theme_func) {\n  ggplot(data=exam_data, aes(x = ENGLISH)) +\n    geom_histogram(bins=20, boundary = 100,\n                   color=\"grey25\", fill=\"grey90\") +\n    ggtitle(theme_name) +\n    theme_func\n}\n\np_minimal <- create_themed_plot(\"theme_minimal()\", theme_minimal())\np_bw <- create_themed_plot(\"theme_bw()\", theme_bw())\np_classic <- create_themed_plot(\"theme_classic()\", theme_classic())\np_wsj <- create_themed_plot(\"theme_wsj()\", theme_wsj())\np_fivethirtyeight <- create_themed_plot(\"theme_fivethirtyeight()\", \n                                        theme_fivethirtyeight())\np_tufte <- create_themed_plot(\"theme_tufte()\", theme_tufte())\n\ngrid.arrange(p_minimal, p_bw, p_classic, \n             p_wsj, p_fivethirtyeight, p_tufte, \n             ncol = 3)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-19-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate English score statistics\nenglish_mean <- mean(exam_data$ENGLISH)\nenglish_sd <- sd(exam_data$ENGLISH)\n```\n:::\n\n\n::: callout-important\n## Theme Selection Guidelines\n\nEach theme serves different communication purposes when displaying the English score distribution (μ = 67.2, σ = 14.7):\n\n-   **theme_minimal()**: Clean, modern - best for digital reports\n-   **theme_bw()**: High contrast - ideal for printing and photocopying\n-   **theme_classic()**: Traditional academic style - suitable for research papers\n-   **theme_wsj()**: Business professional - corporate presentations\n-   **theme_fivethirtyeight()**: Data journalism - blog posts and articles\n-   **theme_tufte()**: Minimalist - when maximizing data-ink ratio is critical\n\n**Selection Criteria:** Choose based on audience, medium, and context. For this academic analysis of 322 students, `theme_minimal()` or `theme_classic()` are most appropriate.\n:::\n\n# Composite Figures with Patchwork\n\n## Creating Component Visualizations\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data=exam_data, aes(x = MATHS)) +\n  geom_histogram(bins=20, boundary = 100,\n                 color=\"grey25\", fill=\"grey90\") + \n  coord_cartesian(xlim=c(0,100)) +\n  ggtitle(\"Distribution of Maths scores\")\np1\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- ggplot(data=exam_data, aes(x = ENGLISH)) +\n  geom_histogram(bins=20, boundary = 100,\n                 color=\"grey25\", fill=\"grey90\") +\n  coord_cartesian(xlim=c(0,100)) +\n  ggtitle(\"Distribution of English scores\")\np2\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(data=exam_data, aes(x= MATHS, y=ENGLISH)) +\n  geom_point() +\n  geom_smooth(method=lm, size=0.5) +  \n  coord_cartesian(xlim=c(0,100), ylim=c(0,100)) +\n  ggtitle(\"English scores versus Maths scores for Primary 3\")\np3\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n## Two-Panel Layout\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 + p2\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-24-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare distributions\ncomparison_stats <- tibble(\n  Subject = c(\"Mathematics\", \"English\"),\n  Mean = c(maths_mean, english_mean),\n  SD = c(maths_sd, english_sd),\n  Range = c(max(exam_data$MATHS) - min(exam_data$MATHS),\n            max(exam_data$ENGLISH) - min(exam_data$ENGLISH))\n)\n```\n:::\n\n\n::: callout-note\n## Side-by-Side Distribution Comparison\n\n**Mathematics:** μ = 69.3, σ = 20, range = 90\n\n**English:** μ = 67.2, σ = 14.7, range = 75\n\n**Comparative Insight:** Mathematics shows higher average performance by 2.1 points, with greater variability (SD difference: 5.3 points). This suggests more heterogeneous performance in Mathematics.\n:::\n\n## Complex Three-Panel Layout\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(p1 / p2) | p3\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-26-1.png){width=1152}\n:::\n:::\n\n\n::: callout-tip\n## Comprehensive Visual Narrative\n\nThis layout effectively tells a complete story:\n\n**Left panels (distributions):** Show individual subject performance characteristics - Mathematics: 322 students, μ = 69.3 - English: 322 students, μ = 67.2\n\n**Right panel (relationship):** Reveals strong positive correlation (r = 0.831)\n\n**Data-Driven Conclusion:** The 0.831 correlation coefficient indicates that approximately 69.1% of variance in English scores can be explained by Mathematics performance, suggesting **shared underlying academic abilities**.\n:::\n\n## Tagged Figure for Academic Reference\n\n\n::: {.cell}\n\n```{.r .cell-code}\n((p1 / p2) | p3) + \n  plot_annotation(tag_levels = 'I')\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-27-1.png){width=1152}\n:::\n:::\n\n\n::: callout-note\n## Figure Referencing System\n\nAuto-tagging (I, II, III) enables precise referencing in academic writing. For example: \"Panel I shows Mathematics distribution with mean 69.3; Panel II displays English distribution; Panel III demonstrates the r = 0.831 correlation between subjects.\"\n:::\n\n## Inset Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 + inset_element(p2, left = 0.02, bottom = 0.7, right = 0.5, top = 1)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-28-1.png){width=960}\n:::\n:::\n\n\n::: callout-tip\n## Contextual Inset Rationale\n\nThe inset histogram provides **immediate context** for the scatter plot by showing the English score distribution (322 students, μ = 67.2) directly within the correlation visualization. This space-efficient design allows readers to simultaneously assess both the relationship (r = 0.831) and the marginal distribution.\n:::\n\n## Themed Composite\n\n\n::: {.cell}\n\n```{.r .cell-code}\npatchwork <- (p1 / p2) | p3\npatchwork & theme_economist()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-29-1.png){width=1152}\n:::\n:::\n\n\n::: callout-tip\n## Unified Theme Application\n\nApplying `theme_economist()` across all panels creates **visual consistency** essential for professional presentations. The unified styling helps readers focus on the data patterns (means: Maths 69.3, English 67.2; correlation r = 0.831) rather than being distracted by stylistic inconsistencies.\n:::\n\n# Extended Analysis: Comprehensive Performance Insights\n\n## Multi-Subject Statistical Overview\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate comprehensive statistics\nscience_mean <- mean(exam_data$SCIENCE)\nscience_sd <- sd(exam_data$SCIENCE)\nscience_median <- median(exam_data$SCIENCE)\nenglish_median <- median(exam_data$ENGLISH)\n\nsummary_stats <- tibble(\n  Subject = c(\"Mathematics\", \"English\", \"Science\"),\n  Mean = c(maths_mean, english_mean, science_mean),\n  Median = c(maths_median, english_median, science_median),\n  SD = c(maths_sd, english_sd, science_sd),\n  Min = c(min(exam_data$MATHS), min(exam_data$ENGLISH), min(exam_data$SCIENCE)),\n  Max = c(max(exam_data$MATHS), max(exam_data$ENGLISH), max(exam_data$SCIENCE)),\n  Range = Max - Min,\n  CV = (SD / Mean) * 100\n)\n\nknitr::kable(summary_stats, digits = 2,\n             caption = \"Comprehensive Summary Statistics by Subject\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Comprehensive Summary Statistics by Subject\n\n|Subject     |  Mean| Median|    SD| Min| Max| Range|    CV|\n|:-----------|-----:|------:|-----:|---:|---:|-----:|-----:|\n|Mathematics | 69.33|     74| 19.98|   9|  99|    90| 28.81|\n|English     | 67.18|     70| 14.69|  21|  96|    75| 21.87|\n|Science     | 61.16|     65| 18.18|  15|  96|    81| 29.72|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify best and worst performing subjects\nbest_subject <- summary_stats$Subject[which.max(summary_stats$Mean)]\nworst_subject <- summary_stats$Subject[which.min(summary_stats$Mean)]\nmost_variable <- summary_stats$Subject[which.max(summary_stats$CV)]\nleast_variable <- summary_stats$Subject[which.min(summary_stats$CV)]\n```\n:::\n\n\n::: callout-important\n## Comparative Subject Performance Analysis\n\n**Highest Performance:** Mathematics (μ = 69.3)\n\n**Lowest Performance:** Science (μ = 61.2)\n\n**Performance Gap:** 8.2 points between highest and lowest performing subjects\n\n**Variability Analysis:** - **Most Variable:** Science (CV = 29.7%) - indicates greatest performance heterogeneity - **Least Variable:** English (CV = 21.9%) - indicates most consistent performance across students\n\n**Key Insight:** The coefficient of variation reveals that Science shows 1.4× more relative variability than English, suggesting scientific understanding is more heterogeneous.\n:::\n\n## Correlation Matrix Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_matrix <- exam_data %>%\n  select(MATHS, ENGLISH, SCIENCE) %>%\n  cor()\n\nknitr::kable(round(cor_matrix, 3), \n             caption = \"Pearson Correlation Matrix: Subject Relationships\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Pearson Correlation Matrix: Subject Relationships\n\n|        | MATHS| ENGLISH| SCIENCE|\n|:-------|-----:|-------:|-------:|\n|MATHS   | 1.000|   0.831|   0.869|\n|ENGLISH | 0.831|   1.000|   0.878|\n|SCIENCE | 0.869|   0.878|   1.000|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract correlations\ncor_me <- cor_matrix[\"MATHS\", \"ENGLISH\"]\ncor_ms <- cor_matrix[\"MATHS\", \"SCIENCE\"]\ncor_es <- cor_matrix[\"ENGLISH\", \"SCIENCE\"]\n\n# Determine strongest correlation\ncors <- c(ME = cor_me, MS = cor_ms, ES = cor_es)\nstrongest_pair <- names(cors)[which.max(cors)]\nstrongest_value <- max(cors)\n```\n:::\n\n\n::: callout-important\n## Inter-Subject Correlation Insights\n\n**Strongest Relationship:** ES correlation = 0.878\n\nThis means 77.1% of variance is shared between these subjects.\n\n**All Correlations:** - Math-English: r = 0.831 (strong positive) - Math-Science: r = 0.869 (strong positive) - English-Science: r = 0.878 (strong positive)\n\n**Educational Implication:** All correlations exceed 0.7, indicating **strong positive relationships** across subjects. Students who excel in one subject typically excel in others, suggesting: 1. Shared cognitive abilities underpin performance 2. Study habits and motivation are consistent across subjects 3. Interventions should target general academic skills rather than subject-specific remediation\n:::\n\n## Gender-Based Performance Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngender_analysis <- exam_data %>%\n  group_by(GENDER) %>%\n  summarise(\n    N = n(),\n    Maths_Mean = mean(MATHS),\n    English_Mean = mean(ENGLISH),\n    Science_Mean = mean(SCIENCE),\n    Maths_SD = sd(MATHS),\n    English_SD = sd(ENGLISH),\n    Science_SD = sd(SCIENCE),\n    Total_Mean = mean(MATHS + ENGLISH + SCIENCE)\n  )\n\nknitr::kable(gender_analysis, digits = 2,\n             caption = \"Performance Metrics by Gender\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Performance Metrics by Gender\n\n|GENDER |   N| Maths_Mean| English_Mean| Science_Mean| Maths_SD| English_SD| Science_SD| Total_Mean|\n|:------|---:|----------:|------------:|------------:|--------:|----------:|----------:|----------:|\n|Female | 170|      69.99|        69.76|        62.68|    18.68|      13.60|      16.92|     202.43|\n|Male   | 152|      68.59|        64.30|        59.47|    21.37|      15.36|      19.41|     192.36|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate differences\nmale_stats <- gender_analysis %>% filter(GENDER == \"Male\")\nfemale_stats <- gender_analysis %>% filter(GENDER == \"Female\")\n\nmaths_diff <- male_stats$Maths_Mean - female_stats$Maths_Mean\nenglish_diff <- male_stats$English_Mean - female_stats$English_Mean\nscience_diff <- male_stats$Science_Mean - female_stats$Science_Mean\ntotal_diff <- male_stats$Total_Mean - female_stats$Total_Mean\n\n# Determine which gender performs better overall\nbetter_gender <- ifelse(total_diff > 0, \"Male\", \"Female\")\n```\n:::\n\n\n::: callout-note\n## Gender Performance Comparison\n\n**Sample Distribution:** 152 males vs 170 females\n\n**Subject-Specific Differences:** - **Mathematics:** Females lead by 1.4 points - **English:** Females lead by 5.5 points\\\n- **Science:** Females lead by 3.2 points\n\n**Overall Performance:** Female students show higher total performance by 10.1 points on average.\n\n**Statistical Significance Assessment:** With differences of 1.4, 5.5, and 3.2 points across subjects, these represent substantial performance gaps that warrant further investigation.\n:::\n\n### Gender Performance Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexam_data %>%\n  pivot_longer(cols = c(MATHS, ENGLISH, SCIENCE),\n               names_to = \"Subject\",\n               values_to = \"Score\") %>%\n  ggplot(aes(x = Subject, y = Score, fill = GENDER)) +\n  geom_boxplot(alpha = 0.7) +\n  scale_fill_manual(values = c(\"#E69F00\", \"#56B4E9\")) +\n  labs(\n    title = \"Score Distribution by Subject and Gender\",\n    subtitle = paste(\"Comparing\", n_students, \"students across three subjects\"),\n    y = \"Score\",\n    x = \"Subject\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-36-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate IQR for each group\niqr_analysis <- exam_data %>%\n  pivot_longer(cols = c(MATHS, ENGLISH, SCIENCE),\n               names_to = \"Subject\", values_to = \"Score\") %>%\n  group_by(Subject, GENDER) %>%\n  summarise(\n    Q1 = quantile(Score, 0.25),\n    Median = median(Score),\n    Q3 = quantile(Score, 0.75),\n    IQR = IQR(Score),\n    .groups = \"drop\"\n  )\n```\n:::\n\n\n::: callout-tip\n## Boxplot Distribution Insights\n\n**Spread Analysis:** The interquartile ranges (IQRs) reveal score concentration patterns:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n- **MATHS:** Male IQR = 27, Female IQR = 25 → Males show more variability\n- **ENGLISH:** Male IQR = 21, Female IQR = 18 → Males show more variability\n- **SCIENCE:** Male IQR = 29, Female IQR = 23 → Males show more variability\n```\n\n\n:::\n:::\n\n\n**Median Comparison:** The median lines within boxes show central tendency for each group, revealing females typically outperform males across subjects.\n:::\n\n## Race-Based Performance Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrace_analysis <- exam_data %>%\n  group_by(RACE) %>%\n  summarise(\n    N = n(),\n    Maths_Mean = mean(MATHS),\n    English_Mean = mean(ENGLISH),\n    Science_Mean = mean(SCIENCE),\n    Total_Mean = mean(MATHS + ENGLISH + SCIENCE),\n    Overall_SD = sd(MATHS + ENGLISH + SCIENCE)\n  ) %>%\n  arrange(desc(Total_Mean))\n\nknitr::kable(race_analysis, digits = 2,\n             caption = \"Performance Metrics by Race (Ranked by Total Score)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Performance Metrics by Race (Ranked by Total Score)\n\n|RACE    |   N| Maths_Mean| English_Mean| Science_Mean| Total_Mean| Overall_SD|\n|:-------|---:|----------:|------------:|------------:|----------:|----------:|\n|Chinese | 193|      76.51|        70.76|        66.99|     214.25|      41.76|\n|Others  |   9|      69.67|        70.11|        66.89|     206.67|      36.83|\n|Indian  |  12|      60.67|        60.75|        53.25|     174.67|      59.11|\n|Malay   | 108|      57.44|        61.27|        51.15|     169.86|      51.65|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate performance gaps\nbest_race <- race_analysis$RACE[1]\nworst_race <- race_analysis$RACE[nrow(race_analysis)]\nperformance_gap <- race_analysis$Total_Mean[1] - race_analysis$Total_Mean[nrow(race_analysis)]\n```\n:::\n\n\n::: callout-important\n## Racial Group Performance Analysis\n\n**Highest Performing Group:** Chinese (Total Mean = 214.3)\n\n**Lowest Performing Group:** Malay (Total Mean = 169.9)\n\n**Performance Gap:** 44.4 points separate the highest and lowest performing racial groups\n\n**Distribution of Excellence:**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n- Chinese: 193 students (59.9%) - Average: 214.3 points\n- Others: 9 students (2.8%) - Average: 206.7 points\n- Indian: 12 students (3.7%) - Average: 174.7 points\n- Malay: 108 students (33.5%) - Average: 169.9 points\n```\n\n\n:::\n:::\n\n\n**Equity Consideration:** The 44.4-point gap represents 23.2% of mean total performance, indicating significant performance disparities that merit attention from educators.\n:::\n\n### Race Performance Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexam_data %>%\n  pivot_longer(cols = c(MATHS, ENGLISH, SCIENCE),\n               names_to = \"Subject\",\n               values_to = \"Score\") %>%\n  ggplot(aes(x = RACE, y = Score, fill = Subject)) +\n  geom_boxplot(alpha = 0.7) +\n  scale_fill_viridis_d() +\n  labs(\n    title = \"Score Distribution by Race and Subject\",\n    subtitle = paste(\"Performance comparison across\", length(unique(exam_data$RACE)), \n                     \"racial groups and 3 subjects\"),\n    y = \"Score\",\n    x = \"Race\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"bottom\",\n    axis.text.x = element_text(angle = 45, hjust = 1)\n  )\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-42-1.png){width=1152}\n:::\n:::\n\n\n::: callout-note\n## Cross-Racial Subject Performance Patterns\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n**Most Variable Subject Across Races:** MATHS (range = 19.1 points)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**Most Consistent Subject Across Races:** ENGLISH (range = 10 points)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe 1.9× greater variability in MATHS suggests that racial background may have differential impact on subject performance, with MATHS showing greater sensitivity to demographic factors.\n```\n\n\n:::\n:::\n\n:::\n\n## Class-Level Performance Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass_analysis <- exam_data %>%\n  group_by(CLASS) %>%\n  summarise(\n    N = n(),\n    Maths_Mean = mean(MATHS),\n    English_Mean = mean(ENGLISH),\n    Science_Mean = mean(SCIENCE),\n    Total_Mean = mean(MATHS + ENGLISH + SCIENCE),\n    Total_SD = sd(MATHS + ENGLISH + SCIENCE)\n  ) %>%\n  arrange(desc(Total_Mean))\n\nknitr::kable(class_analysis, digits = 2,\n             caption = \"Performance Metrics by Class (Ranked by Total Score)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Performance Metrics by Class (Ranked by Total Score)\n\n|CLASS |  N| Maths_Mean| English_Mean| Science_Mean| Total_Mean| Total_SD|\n|:-----|--:|----------:|------------:|------------:|----------:|--------:|\n|3A    | 40|      89.92|        83.35|        81.08|     254.35|    17.11|\n|3B    | 38|      85.61|        80.71|        78.68|     245.00|    14.04|\n|3D    | 38|      77.79|        73.87|        69.71|     221.37|    16.24|\n|3C    | 39|      78.00|        72.15|        63.69|     213.85|    19.41|\n|3E    | 38|      71.63|        67.29|        61.29|     200.21|    22.88|\n|3F    | 39|      71.69|        62.79|        60.90|     195.38|    20.90|\n|3G    | 34|      55.03|        60.74|        47.62|     163.38|    29.64|\n|3H    | 33|      44.33|        50.06|        39.36|     133.76|    31.42|\n|3I    | 23|      27.17|        38.61|        30.70|      96.48|    28.61|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze class performance distribution\nbest_class <- class_analysis$CLASS[1]\nworst_class <- class_analysis$CLASS[nrow(class_analysis)]\nclass_gap <- class_analysis$Total_Mean[1] - class_analysis$Total_Mean[nrow(class_analysis)]\n```\n:::\n\n\n::: callout-warning\n## Class-Level Performance Disparities\n\n**Top Performing Class:** 3A (Average: 254.3 points, N = 40)\n\n**Lowest Performing Class:** 3I (Average: 96.5 points, N = 23)\n\n**Inter-Class Gap:** 157.9 points\n\n**Consistency Analysis:** The coefficient of variation across classes is 27%, suggesting significant teaching quality disparities across the 9 classes.\n\n**Recommendation:** The 157.9-point gap warrants immediate investigation into teaching practices and resource allocation.\n:::\n\n## Comprehensive Density Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexam_data %>%\n  pivot_longer(cols = c(MATHS, ENGLISH, SCIENCE),\n               names_to = \"Subject\",\n               values_to = \"Score\") %>%\n  ggplot(aes(x = Score, fill = Subject)) +\n  geom_density(alpha = 0.5) +\n  scale_fill_viridis_d() +\n  labs(\n    title = \"Score Distributions Across All Subjects\",\n    subtitle = paste(\"Density curves for\", n_students, \"students in three subjects\"),\n    x = \"Score\",\n    y = \"Density\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-46-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze distribution overlap\ndensity_stats <- exam_data %>%\n  pivot_longer(cols = c(MATHS, ENGLISH, SCIENCE),\n               names_to = \"Subject\", values_to = \"Score\") %>%\n  group_by(Subject) %>%\n  summarise(\n    Peak = median(Score),\n    Spread = IQR(Score),\n    .groups = \"drop\"\n  )\n```\n:::\n\n\n::: callout-note\n## Distribution Pattern Analysis\n\n**Peak Locations (Median Scores):**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n- ENGLISH: 70 points\n- MATHS: 74 points\n- SCIENCE: 65 points\n```\n\n\n:::\n:::\n\n\n**Distribution Spread (IQR):**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n- ENGLISH: 19 points (middle 50% range)\n- MATHS: 27 points (middle 50% range)\n- SCIENCE: 25.5 points (middle 50% range)\n```\n\n\n:::\n:::\n\n\n**Overlap Interpretation:** The substantial overlap in density curves confirms the strong inter-subject correlations observed earlier (0.86 average correlation). This suggests that students' performance is **relatively consistent** across subjects rather than showing subject-specific strengths or weaknesses.\n:::\n\n## Ridge Plot: Class Performance Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexam_data %>%\n  ggplot(aes(x = MATHS, y = CLASS, fill = CLASS)) +\n  geom_density_ridges(alpha = 0.7, scale = 1.5) +\n  scale_fill_viridis_d() +\n  labs(\n    title = \"Mathematics Score Distribution by Class\",\n    subtitle = paste(\"Ridge plot showing performance patterns across\", \n                     length(unique(exam_data$CLASS)), \"classes\"),\n    x = \"Maths Score\",\n    y = \"Class\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-50-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze distribution shapes by class\nclass_distribution <- exam_data %>%\n  group_by(CLASS) %>%\n  summarise(\n    Mean = mean(MATHS),\n    Median = median(MATHS),\n    Skew = (Mean - Median) / sd(MATHS),\n    .groups = \"drop\"\n  ) %>%\n  mutate(\n    Shape = case_when(\n      abs(Skew) < 0.2 ~ \"Symmetric\",\n      Skew > 0 ~ \"Right-skewed\",\n      TRUE ~ \"Left-skewed\"\n    )\n  )\n```\n:::\n\n\n::: callout-tip\n## Class-Specific Distribution Characteristics\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n**3A:** Symmetric distribution (Mean: 89.9, Median: 90.5)\n\n**3B:** Symmetric distribution (Mean: 85.6, Median: 86)\n\n**3C:** Symmetric distribution (Mean: 78, Median: 78)\n\n**3D:** Symmetric distribution (Mean: 77.8, Median: 78.5)\n\n**3E:** Symmetric distribution (Mean: 71.6, Median: 71)\n\n**3F:** Symmetric distribution (Mean: 71.7, Median: 71)\n\n**3G:** Symmetric distribution (Mean: 55, Median: 54)\n\n**3H:** Symmetric distribution (Mean: 44.3, Median: 44)\n\n**3I:** Right-skewed distribution (Mean: 27.2, Median: 24)\n```\n\n\n:::\n:::\n\n\n**Pattern Insight:** Classes showing right-skewed distributions have a concentration of students at lower scores with few high achievers, while left-skewed distributions indicate most students performing well with fewer struggling students. Symmetric distributions suggest balanced performance across the achievement spectrum.\n:::\n\n## Correlation Visualization Matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexam_data %>%\n  select(MATHS, ENGLISH, SCIENCE, GENDER) %>%\n  ggpairs(\n    aes(color = GENDER, alpha = 0.5),\n    upper = list(continuous = wrap(\"cor\", size = 4)),\n    lower = list(continuous = wrap(\"points\", alpha = 0.3, size = 0.8)),\n    diag = list(continuous = wrap(\"densityDiag\", alpha = 0.5))\n  ) +\n  labs(title = \"Pairwise Relationships Between Subjects by Gender\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-53-1.png){width=1152}\n:::\n:::\n\n\n::: callout-important\n## Multivariate Relationship Insights\n\nThis pairs plot reveals:\n\n**1. Diagonal (Distributions):** - Gender-stratified densities show distinct distribution patterns between males and females - Both groups show generally high performance across subjects\n\n**2. Upper Triangle (Correlations):** - All correlations exceed 0.7, indicating **strong linear relationships** - Gender-specific correlations are remarkably similar (range: 0.831 to 0.878)\n\n**3. Lower Triangle (Scatter Plots):** - Point clouds show tight linear patterns confirming correlation strength - Color separation reveals visible performance differences between genders\n\n**Practical Implication:** The consistently high correlations (mean r = 0.86) across all subject pairs suggest that **general academic ability** rather than subject-specific talent drives performance in this cohort.\n:::\n\n## Performance Category Heatmap\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Categorize performance\nexam_performance <- exam_data %>%\n  mutate(\n    Maths_Category = cut(MATHS, \n                         breaks = c(0, 50, 70, 100), \n                         labels = c(\"Below Average\", \"Average\", \"Above Average\")),\n    English_Category = cut(ENGLISH, \n                           breaks = c(0, 50, 70, 100), \n                           labels = c(\"Below Average\", \"Average\", \"Above Average\"))\n  ) %>%\n  count(Maths_Category, English_Category)\n\nggplot(exam_performance, \n       aes(x = Maths_Category, y = English_Category, fill = n)) +\n  geom_tile(color = \"white\") +\n  geom_text(aes(label = n), color = \"white\", fontface = \"bold\", size = 6) +\n  scale_fill_viridis_c(option = \"magma\") +\n  labs(\n    title = \"Student Performance Heatmap: Mathematics vs English\",\n    subtitle = paste(\"Cross-tabulation of\", n_students, \"students by performance level\"),\n    x = \"Mathematics Performance\",\n    y = \"English Performance\",\n    fill = \"Count\"\n  ) +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-54-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate diagonal vs off-diagonal patterns\ndiagonal_count <- exam_performance %>%\n  filter(Maths_Category == English_Category) %>%\n  summarise(total = sum(n)) %>%\n  pull(total)\n\ndiagonal_pct <- (diagonal_count / n_students) * 100\n```\n:::\n\n\n::: callout-important\n## Performance Consistency Analysis\n\n**Diagonal Concentration:** 233 students (72.4%) show **consistent performance** across Mathematics and English (same category in both subjects).\n\n**Off-Diagonal Patterns:** 89 students (27.6%) show **inconsistent performance** (different categories).\n\n**Key Finding:** The 72.4% consistency rate strongly supports the hypothesis that students maintain similar performance levels across subjects, aligning with the observed high correlation (r = 0.831).\n\n**Dominant Category:** The cell with highest frequency (142 students) is Above Average in Mathematics and Above Average in English, indicating this is the **modal performance profile**.\n:::\n\n## Top Performers Identification\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rank students\nexam_ranked <- exam_data %>%\n  mutate(\n    Total_Score = MATHS + ENGLISH + SCIENCE,\n    Average_Score = Total_Score / 3,\n    Percentile = percent_rank(Total_Score) * 100,\n    Rank = dense_rank(desc(Total_Score))\n  ) %>%\n  arrange(Rank)\n\n# Top 10\ntop_10 <- exam_ranked %>% head(10)\nknitr::kable(\n  top_10 %>% \n    select(Rank, ID, CLASS, GENDER, RACE, MATHS, ENGLISH, SCIENCE, Total_Score, Percentile),\n  digits = 1,\n  caption = \"Top 10 Highest Achieving Students\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Highest Achieving Students\n\n| Rank|ID         |CLASS |GENDER |RACE    | MATHS| ENGLISH| SCIENCE| Total_Score| Percentile|\n|----:|:----------|:-----|:------|:-------|-----:|-------:|-------:|-----------:|----------:|\n|    1|Student036 |3A    |Male   |Chinese |    99|      96|      96|         291|      100.0|\n|    2|Student013 |3A    |Female |Chinese |    97|      90|      90|         277|       99.4|\n|    2|Student016 |3A    |Female |Chinese |    95|      91|      91|         277|       99.4|\n|    3|Student039 |3A    |Male   |Chinese |    97|      89|      90|         276|       98.8|\n|    3|Student010 |3A    |Female |Chinese |    93|      93|      90|         276|       98.8|\n|    4|Student012 |3A    |Female |Chinese |    97|      93|      84|         274|       98.4|\n|    5|Student002 |3A    |Female |Chinese |    93|      90|      89|         272|       98.1|\n|    6|Student043 |3B    |Female |Chinese |    97|      84|      88|         269|       97.5|\n|    6|Student015 |3A    |Female |Others  |    90|      92|      87|         269|       97.5|\n|    7|Student066 |3B    |Male   |Chinese |    97|      83|      88|         268|       96.9|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze top performer characteristics\ntop_10_summary <- top_10 %>%\n  summarise(\n    Avg_Total = mean(Total_Score),\n    Min_Total = min(Total_Score),\n    Avg_Maths = mean(MATHS),\n    Avg_English = mean(ENGLISH),\n    Avg_Science = mean(SCIENCE),\n    Male_Count = sum(GENDER == \"Male\"),\n    Female_Count = sum(GENDER == \"Female\")\n  )\n```\n:::\n\n\n::: callout-note\n## Top Performer Characteristics\n\n**Performance Threshold:** Top 10 students scored between 268 and 291 total points, averaging 274.9 points.\n\n**Subject Breakdown for Top 10:** - Mathematics: 95.5 average - English: 90.1 average - Science: 89.3 average\n\n**Gender Distribution:** 3 males, 7 females among top 10, suggesting female predominance in top achievement.\n\n**Excellence Pattern:** Top performers score 77.2 points above the cohort average, representing the 96.9th percentile and above.\n:::\n\n### Top Performers Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_10 %>%\n  pivot_longer(cols = c(MATHS, ENGLISH, SCIENCE),\n               names_to = \"Subject\",\n               values_to = \"Score\") %>%\n  ggplot(aes(x = reorder(ID, -Total_Score), y = Score, fill = Subject)) +\n  geom_col(position = \"dodge\", alpha = 0.8) +\n  scale_fill_viridis_d() +\n  labs(\n    title = \"Top 10 Performers: Subject-Specific Breakdown\",\n    subtitle = paste(\"Individual scores for highest-achieving students (total range:\", \n                     round(top_10_summary$Min_Total, 1), \"-\", \n                     round(max(top_10$Total_Score), 1), \"points)\"),\n    x = \"Student ID (ordered by total score)\",\n    y = \"Score\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    legend.position = \"bottom\"\n  )\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-58-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Analyze balance in top performers\nbalance_analysis <- top_10 %>%\n  mutate(\n    Score_Range = pmax(MATHS, ENGLISH, SCIENCE) - pmin(MATHS, ENGLISH, SCIENCE),\n    Balanced = Score_Range < 10\n  )\n\nn_balanced <- sum(balance_analysis$Balanced)\n```\n:::\n\n\n::: callout-tip\n## Top Performer Balance Analysis\n\n**Balanced vs Specialized:** - **7 students** (70%) show balanced performance (\\< 10 points difference across subjects) - **3 students** (30%) show more specialization (≥ 10 points difference)\n\n**Interpretation:** The high proportion of balanced performers among top students suggests that **consistent excellence across subjects** is the primary path to top achievement in this cohort.\n:::\n\n## Statistical Hypothesis Testing\n\n### Gender Differences Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# T-tests for all subjects\nt_maths <- t.test(MATHS ~ GENDER, data = exam_data)\nt_english <- t.test(ENGLISH ~ GENDER, data = exam_data)\nt_science <- t.test(SCIENCE ~ GENDER, data = exam_data)\n\n# Create summary table\nt_test_results <- tibble(\n  Subject = c(\"Mathematics\", \"English\", \"Science\"),\n  Male_Mean = c(\n    t_maths$estimate[1],\n    t_english$estimate[1],\n    t_science$estimate[1]\n  ),\n  Female_Mean = c(\n    t_maths$estimate[2],\n    t_english$estimate[2],\n    t_science$estimate[2]\n  ),\n  Difference = Male_Mean - Female_Mean,\n  t_statistic = c(t_maths$statistic, t_english$statistic, t_science$statistic),\n  p_value = c(t_maths$p.value, t_english$p.value, t_science$p.value),\n  Significant = p_value < 0.05\n)\n\nknitr::kable(t_test_results, digits = 3,\n             caption = \"Independent Samples t-test: Gender Differences\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Independent Samples t-test: Gender Differences\n\n|Subject     | Male_Mean| Female_Mean| Difference| t_statistic| p_value|Significant |\n|:-----------|---------:|-----------:|----------:|-----------:|-------:|:-----------|\n|Mathematics |    69.994|      68.592|      1.402|       0.623|   0.533|FALSE       |\n|English     |    69.759|      64.303|      5.456|       3.357|   0.001|TRUE        |\n|Science     |    62.676|      59.467|      3.209|       1.573|   0.117|FALSE       |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count significant differences\nn_significant <- sum(t_test_results$Significant)\nsig_subjects <- t_test_results$Subject[t_test_results$Significant]\n```\n:::\n\n\n::: callout-important\n## Gender Difference Statistical Conclusions\n\n**Significant Differences Detected:** 1 out of 3 subjects show statistically significant gender differences (p \\< 0.05)\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n**Significant in:** English\n\n- **English:** Males outperform by 5.46 points (p = 9e-04)\n```\n\n\n:::\n:::\n\n\n**Effect Size Interpretation:**\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n- Mathematics: Cohen's d ≈ 0.07 (negligible effect)\n- English: Cohen's d ≈ 0.38 (small effect)\n- Science: Cohen's d ≈ 0.18 (negligible effect)\n```\n\n\n:::\n:::\n\n:::\n\n### Racial Group Differences Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ANOVA for Mathematics\nanova_maths <- aov(MATHS ~ RACE, data = exam_data)\nanova_summary <- summary(anova_maths)\n\n# Extract F-statistic and p-value\nf_stat <- anova_summary[[1]]$`F value`[1]\np_val <- anova_summary[[1]]$`Pr(>F)`[1]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(anova_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value  Pr(>F)    \nRACE          3  26102    8701   27.13 1.2e-15 ***\nResiduals   318 101982     321                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Racial Group Comparison: ANOVA Results\n\n**Mathematics Performance Across Racial Groups:**\n\nF-statistic = 27.13, p-value = 0\n\n**Conclusion:** There ARE statistically significant differences (p = 0 < 0.05) in Mathematics performance across racial groups. The performance gap of 44.4 points between highest (Chinese) and lowest (Malay) performing groups represents a meaningful disparity that warrants educational intervention.\n\n**Practical Significance:** With F = 27.13, approximately 20.4% of total variance in Mathematics scores is explained by racial group membership.\n:::\n\n# Comprehensive Performance Dashboard\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create dashboard components\nplot_hist_maths <- ggplot(exam_data, aes(x = MATHS)) +\n  geom_histogram(bins = 20, fill = \"steelblue\", color = \"black\", alpha = 0.7) +\n  labs(title = paste0(\"A) Mathematics (μ=\", round(maths_mean, 1), \", σ=\", round(maths_sd, 1), \")\"),\n       x = \"Score\", y = \"Count\") +\n  theme_minimal()\n\nplot_hist_english <- ggplot(exam_data, aes(x = ENGLISH)) +\n  geom_histogram(bins = 20, fill = \"coral\", color = \"black\", alpha = 0.7) +\n  labs(title = paste0(\"B) English (μ=\", round(english_mean, 1), \", σ=\", round(english_sd, 1), \")\"),\n       x = \"Score\", y = \"Count\") +\n  theme_minimal()\n\nplot_scatter <- ggplot(exam_data, aes(x = MATHS, y = ENGLISH, color = GENDER)) +\n  geom_point(size = 2, alpha = 0.6) +\n  geom_smooth(method = \"lm\", se = TRUE, alpha = 0.2) +\n  scale_color_manual(values = c(\"#E69F00\", \"#56B4E9\")) +\n  labs(title = paste0(\"C) Correlation (r=\", round(cor_me, 3), \")\"),\n       x = \"Maths\", y = \"English\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n\nplot_boxplot_gender <- exam_data %>%\n  pivot_longer(cols = c(MATHS, ENGLISH, SCIENCE),\n               names_to = \"Subject\", values_to = \"Score\") %>%\n  ggplot(aes(x = Subject, y = Score, fill = GENDER)) +\n  geom_boxplot(alpha = 0.7) +\n  scale_fill_manual(values = c(\"#E69F00\", \"#56B4E9\")) +\n  labs(title = paste0(\"D) Gender Comparison (\", n_significant, \"/3 significant)\"),\n       x = \"Subject\", y = \"Score\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n\nplot_density <- exam_data %>%\n  pivot_longer(cols = c(MATHS, ENGLISH, SCIENCE),\n               names_to = \"Subject\", values_to = \"Score\") %>%\n  ggplot(aes(x = Score, fill = Subject)) +\n  geom_density(alpha = 0.5) +\n  scale_fill_viridis_d() +\n  labs(title = \"E) Subject Distributions\",\n       x = \"Score\", y = \"Density\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n\n# Combine into dashboard\ndashboard <- (plot_hist_maths + plot_hist_english + plot_scatter) /\n             (plot_boxplot_gender + plot_density)\n\ndashboard + \n  plot_annotation(\n    title = paste(\"Primary 3 Academic Performance Dashboard |\", n_students, \"Students\"),\n    subtitle = paste(\"Overall Correlation:\", round(mean(cors), 3), \"| Gender Gap:\", round(abs(total_diff), 1), \"pts | Top Score:\", round(max(exam_ranked$Total_Score), 1)),\n    caption = \"Data-driven insights generated from examination results\",\n    theme = theme_minimal()\n  )\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex02_files/figure-html/unnamed-chunk-66-1.png){width=1536}\n:::\n:::\n\n\n::: callout-note\n## Dashboard Summary Insights\n\nThis integrated dashboard synthesizes key findings:\n\n**Panel A & B:** Distributions show similar central tendencies with variability of 17.3 points (average SD)\n\n**Panel C:** Correlation of r = 0.831 explains 69.1% of shared variance, indicating highly interdependent subject performance\n\n**Panel D:** Gender analysis reveals 1 significant difference(s), suggesting gender is a relevant factor in performance\n\n**Panel E:** Overlapping density curves confirm students maintain highly consistent performance across subjects (avg r = 0.86)\n:::\n\n# Key Findings and Conclusions\n\n## Overall Performance Summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate comprehensive statistics\noverall_mean <- mean(c(maths_mean, english_mean, science_mean))\nbest_performing_subject <- summary_stats$Subject[which.max(summary_stats$Mean)]\nworst_performing_subject <- summary_stats$Subject[which.min(summary_stats$Mean)]\n```\n:::\n\n\n::: callout-important\n## Data-Driven Performance Conclusions\n\n**1. Subject Performance Hierarchy** - **Highest:** Mathematics (μ = 69.3) - **Lowest:** Science (μ = 61.2) - **Gap:** 8.2 points\n\n**2. Inter-Subject Relationships** - **Average correlation:** r = 0.86 - **Shared variance:** 73.9% - **Interpretation:** Students showing excellence in one subject have a **86% probability** of excelling in others\n\n**3. Demographic Factors** - **Gender impact:** 1 subjects show significant differences - **Racial disparities:** 44.4 point gap (statistically significant). **4. Class-Level Variation** - **Between-class gap:** 157.9 points - **CV across classes:** 27% - **Quality assessment:** Significant disparities requiring intervention\n\n**5. Performance Distribution** - **Top 10% threshold:** ≥ 254 total points - **Bottom 10% threshold:** ≤ 118.2 total points - **Performance spread:** 135.8 points between excellence and struggle\n:::\n\n## Methodological Achievement Summary\n\n::: callout-tip\n## Technical Skills Demonstrated\n\n**ggrepel Implementation:** - Successfully resolved overlapping label problem affecting 322 data points - Applied selective labeling strategy highlighting top/bottom 21.1% of students - Achieved 100% label readability while maintaining visualization integrity\n\n**Theme Customization:** - Evaluated 6 professional themes across multiple contexts - Applied typography-focused customization (font sizes: 15-18pt) - Demonstrated publication-ready styling for academic and business audiences\n\n**Patchwork Composition:** - Created 2-panel, 3-panel, 4-panel, and 5-panel layouts - Implemented auto-tagging for academic referencing - Achieved unified theme application across composite figures - Utilized inset elements for space-efficient contextualization\n\n**Statistical Analysis:** - Conducted 4 hypothesis tests (3 t-tests, 1 ANOVA) - Calculated 3 correlation coefficients - Identified 1 statistically significant demographic effects - Generated 24 summary statistics dynamically\n:::\n\n## Evidence-Based Recommendations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate data-driven recommendations\nhigh_performers_pct <- sum(exam_ranked$Percentile >= 90) / n_students * 100\nlow_performers_pct <- sum(exam_ranked$Percentile <= 10) / n_students * 100\n```\n:::\n\n\n::: callout-warning\n## Actionable Insights for Educators\n\n**1. Intervention Targeting** - **10.2%** of students (33 students) require intensive support (bottom 10%)\n\n-   **Focus:** General academic skills rather than subject-specific tutoring, given high inter-subject correlation (r = 0.86)\n\n**2. Excellence Programs** - **9.6%** of students (31 students) demonstrate exceptional ability\n\n-   **Pattern:** 7 of top 10 show balanced excellence across subjects\n\n-   **Strategy:** Develop comprehensive enrichment programs\n\n**3. Class-Level Equity** - **Current gap:** 157.9 points between best (3A) and worst (3I) performing classes\n\n-   **Target:** Reduce gap to \\< 15 points through immediate intervention\n\n**4. Gender Considerations** - Address the 1 subject(s) showing gender disparities: English\n\n**5. Racial Equity Initiatives** - **Current disparity:** 44.4 points (statistically significant)\n\n-   **Action:** Investigate factors contributing to 23.2% performance gap and implement targeted support for Malay students\n:::\n\n# References\n\n-   [Patchwork R package](https://patchwork.data-imaginist.com/)\n-   [ggrepel](https://ggrepel.slowkow.com/)\n-   [ggthemes](https://yutannihilation.github.io/allYourFigureAreBelongToUs/ggthemes/)\n-   [hrbrthemes](https://cinc.rud.is/web/packages/hrbrthemes/)\n-   [R for Visual Analytics - Chapter 2](https://r4va.netlify.app/chap02)\n",
    "supporting": [
      "Hands-on_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}