project:
  type: website
  output-dir: _site

website:
  title: "ISSS608"
  navbar:
    background: "#3b4d5c"
    foreground: "#ffffff"
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Excercises-1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
          - text: "Hands-on Excercises-2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html
          - text: "Hands-on Excercises-3a"
            href: Hands-on_Ex/Hands-on_Ex03a/Hands-on_Ex03a.html
          - text: "Hands-on Excercises-3b"
            href: Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html
      - text: "In-class Excercises"
        menu:
          - text: "In-class Excercises-1 (Self Exploration)"
            href: In_class_Ex/In_class_Ex01/In_class_ex01.html
          - text: "In-class Excercises-2"
            href: In_class_Ex/In_class_Ex02/In_class_ex02.html
    right:
      - text: "About"
        href: https://haleyhome.vercel.app
      - icon: linkedin
        href: https://www.linkedin.com/in/nameishaleytran/
      - icon: github
        href: https://github.com/HaleyTran2000

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
