project:
  type: website
  output-dir: _site

website:
  title: "ISSS608"
  navbar:
    background: "#3b4d5c"
    foreground: "#ffffff"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Excercises-1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html
    right:
      - text: "About"
        href: about.html
      - icon: linkedin
        href: https://www.linkedin.com/in/nameishaleytran/
      - icon: github
        href: https://github.com/HaleyTran2000

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
